apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: lmlaaak/student-management:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/springdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root123
---
apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  namespace: devops
spec:
  selector:
    app: student-management
  type: NodePort
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30080
